language: "node_js"
node_js:
  - "0.10"
  - "0.12"
  - "4.0"
  - "9.11"
before_install:
  - sudo add-apt-repository -y ppa:vbkaisetsu/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq kytea
  - sudo apt-get install -qq libkytea-dev
  - sudo dpkg -L libkytea-dev
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"

