language: "node_js"
node_js:
  - "0.10"
  - "0.12"
  - "4.0"
  - "6.14"
  - "8.11"
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - wget http://www.phontron.com/kytea/download/kytea-0.4.7.tar.gz
  - tar -xzf kytea-0.4.7.tar.gz
  - cd kytea-0.4.7
  - ./configure
  - make
  - sudo make install
  - sudo ldconfig
  - cd ..
